env:
  node: true
  es2020: true
extends:
  - eslint: recommended
  - plugin: prettier/recommended
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  prettier/prettier:
    - error
    - endOfLine: auto
